name: learn-github-actions
on: [push]
jobs:
  set-matrix:
    runs-on: ubuntu-latest
    steps:
      - name: set-matrix
        id: set-matrix
        run: |
          num=$(echo '["1","2","3"]' | jq -c)
          odd=$(echo '["1","3"]' | jq -c)
          even=$(echo '[""]' | jq -c)
          vowel=$(echo '[""]' | jq -c)
          consonant=$(echo '["B", "C"]' | jq -c)
          echo "num=${num}" >> $GITHUB_OUTPUT
          echo "odd=${odd}" >> $GITHUB_OUTPUT
          echo "even=${even}" >> $GITHUB_OUTPUT
          echo "vowel=${vowel}" >> $GITHUB_OUTPUT
          echo "consonant=${consonant}" >> $GITHUB_OUTPUT
    outputs:
      num: ${{ steps.set-matrix.outputs.num }}
      odd: ${{ steps.set-matrix.outputs.odd }}
      even: ${{ steps.set-matrix.outputs.even }}
      vowel: ${{ steps.set-matrix.outputs.vowel }}
      consonant: ${{ steps.set-matrix.outputs.consonant }}

  build:
    runs-on: ubuntu-latest
    needs: set-matrix
    strategy:
      fail-fast: false
      matrix:
        num: ${{ fromJSON(needs.set-matrix.outputs.num) }}
    steps:
      - name: wait
        run: |
          sleep 10
          echo "timeout"
      - name: main proc
        run: echo ${{ matrix.num }}
      - name: error
        if: |
          matrix.num == '1'
        run: |
          exit 1

  static:
    runs-on: ubuntu-latest
    needs: [set-matrix, build]
    if: |
      needs.build.result == 'success'
    strategy:
      fail-fast: false
      max-parallel: 2
      matrix:
        num: ${{ fromJSON(needs.set-matrix.outputs.num) }}
    steps:
      - name: wait
        run: |
          sleep 10
          echo "timeout"
      - name: main proc
        run: echo ${{ matrix.num }}

  test_odd:
    runs-on: ubuntu-latest
    needs: [set-matrix, static]
    if: |
      !contains(fromJSON(needs.set-matrix.outputs.odd), '')
      && needs.build.result == 'success'
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        odd: ${{ fromJSON(needs.set-matrix.outputs.odd) }}
    steps:
      - name: wait
        run: |
          sleep 10
          echo "timeout"
      - name: main proc
        run: echo ${{ matrix.odd }}

  test_even:
    runs-on: ubuntu-latest
    needs: [set-matrix, static]
    if: |
      !contains(fromJSON(needs.set-matrix.outputs.even), '')
      && needs.build.result == 'success'
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        even: ${{ fromJSON(needs.set-matrix.outputs.even) }}
    steps:
      - name: wait
        run: |
          sleep 10
          echo "timeout"
      - name: main proc
        run: echo ${{ matrix.even }}
      
  test_vowel:
    runs-on: ubuntu-latest
    needs: [set-matrix, test_odd, test_even]
    if: |
      !contains(fromJSON(needs.set-matrix.outputs.vowel), '')
      && needs.build.result == 'success'
    strategy:
      fail-fast: false
      matrix:
        vowel: ${{ fromJSON(needs.set-matrix.outputs.vowel) }}
    steps:
      - name: wait
        run: |
          sleep 10
          echo "timeout"
      - name: main proc
        run: echo ${{ matrix.vowel }}

  test_consonant:
    runs-on: ubuntu-latest
    needs: [set-matrix, test_odd, test_even]
    if: |
      !contains(fromJSON(needs.set-matrix.outputs.consonant), '')
      && needs.build.result == 'success'
    strategy:
      fail-fast: false
      matrix:
        consonant: ${{ fromJSON(needs.set-matrix.outputs.consonant) }}
    steps:
      - name: wait
        run: |
          sleep 10
          echo "timeout"
      - name: main proc
        run: echo ${{ matrix.consonant }}
