name: learn-github-actions
on: [push]
jobs:
  set-matrix:
    runs-on: ubuntu-latest
    steps:
      - name: set-matrix
        id: set-matrix
        run: |
          num=$(echo '["1","2","3"]' | jq -c)
          txt=$(echo '["A","B","C"]' | jq -c)
          echo "::set-output name=output1::${num}"
          echo "::set-output name=output2::${txt}"
    outputs:
      output1: ${{ steps.set-matrix.outputs.output1 }}
      output2: ${{ steps.set-matrix.outputs.output2 }}

  build:
    runs-on: ubuntu-latest
    needs: set-matrix
    strategy:
      fail-fast: false
      matrix:
        num: ${{ fromJson(needs.set-matrix.outputs.output1) }}
    steps:
      - run: sleep 10
      - run: echo ${{ matrix.num }}

  static:
    runs-on: ubuntu-latest
    needs: [set-matrix, build]
    strategy:
      fail-fast: false
      max-parallel: 2
      matrix:
        txt: ${{ fromJson(needs.set-matrix.outputs.output2) }}
    steps:
      - run: sleep 10
      - run: echo ${{ matrix.txt }}

  test_A1:
    runs-on: ubuntu-latest
    needs: [set-matrix, static]
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        num: ${{ fromJson(needs.set-matrix.outputs.output1) }}
    steps:
      - run: sleep 10
      - run: echo ${{ matrix.num }}

  test_A2:
    runs-on: ubuntu-latest
    needs: [set-matrix, static]
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        txt: ${{ fromJson(needs.set-matrix.outputs.output2) }}
    steps:
      - run: sleep 10
      - run: echo ${{ matrix.txt }}
      
  test_B1:
    runs-on: ubuntu-latest
    needs: [set-matrix, test_A1, test_A2]
    strategy:
      fail-fast: false
      matrix:
        num: ${{ fromJson(needs.set-matrix.outputs.output1) }}
    steps:
      - run: sleep 10
      - run: echo ${{ matrix.num }}

  test_B2:
    runs-on: ubuntu-latest
    needs: [set-matrix, test_A1, test_A2]
    strategy:
      fail-fast: false
      matrix:
        txt: ${{ fromJson(needs.set-matrix.outputs.output2) }}
    steps:
      - run: sleep 10
      - run: echo ${{ matrix.txt }}
